### ISSUE TITLE
Make `execute()`'s `options` parameter optional

### ISSUE THREAD

**Issue by robertbullen** [thiamsantos/invisible-grecaptcha#11]
In a previous PR, I declared `execute()`'s `options` parameter as optional in the TypeScript definitions. But that is an incorrect interpretation of how the function is currently written. As it is now, all the properties of `options` are assigned to local variables via destructuring with default values. However, destructuring doesn't work against an undefined object, which means that `options` is a required parameter. In fact, the demo site is broken for this very reason and throws the following error:

```javascript
Uncaught TypeError: Cannot read property 'locale' of undefined
    at Object.e.execute (index.js:18)
    at HTMLButtonElement.<anonymous> (index.js:4)
```

But given that both @thiamsantos and I have made the same mistake in this regard, and it seems silly to force callers to allocate an empty object when calling `execute()` and no customization is needed, it is more intuitive that the `options` parameter should be optional.

I'll have a PR for this issue soon.

**Comment by thiamsantos** [comment]
I think that just adding a empty as default argument should do the trick.

```diff
- export function execute(sitekey, {locale = 'en', position = 'bottomright'}) {
+ export function execute(sitekey, {locale = 'en', position = 'bottomright'} = {}) {
```
