### ISSUE TITLE
Streamline `execute()`

### ISSUE THREAD

**Issue by robertbullen** [thiamsantos/invisible-grecaptcha#13]
There are two motivations for this issue:

1. `execute()` is creating two promises, one nested within the other. The second one is not necessary.
2. `execute()` is checking whether Google's reCAPTCHA library has been loaded before calling `loadScript()`. I think `loadScript()` should perform that check as a clearer separation of concerns.

A PR is forthcoming.

**Comment by thiamsantos** [comment]
> execute() is creating two promises, one nested within the other. The second one is not necessary.

You are completely right, I don't know why I did that. :thinking: 

> execute() is checking whether Google's reCAPTCHA library has been loaded before calling loadScript(). I think loadScript() should perform that check as a clearer separation of concerns.

What do you mean by that?

**Comment by robertbullen** [comment]
I mean that `loadScript()`, and only `loadScript()`, should worry about whether Google's reCAPTCHA library has been loaded and do so if necessary. But right now `execute()` kinda worries about it a little bit too because it checks for `window.grecaptcha` before calling `loadScript()`.

I think `execute()` should call `loadScript()` unconditionally and then let `loadScript()` do the `window.grecaptcha` check and load the library if necessary or do nothing if not necessary. Furthermore, `loadScript()` can cache the async promise that it creates and simply return it from that point forward.

**Comment by thiamsantos** [comment]
@robertbullen I see, you are completely right.

**Comment by robertbullen** [comment]
I have updated code just about ready for your review. I just want to test it first...
